# Generated by Django 3.2.6 on 2021-10-05 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
