# Generated by Django 3.2.8 on 2021-10-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_status',
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=8)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='auctions.listing')),
            ],
        ),
    ]
