# Generated by Django 3.2.8 on 2021-10-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20211013_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('image_url__isnull', False), ('photo__isnull', True)), models.Q(('image_url__isnull', True), ('photo__isnull', False)), _connector='OR'), name='auctions_listing_file_or_url'),
        ),
    ]
