# Generated by Django 3.2.8 on 2021-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20211014_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
