# Generated by Django 3.2.8 on 2021-10-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
